### ISSUE TITLE
ترتیب نمایش دسته ها در صفحه اول از مدیریت اعمال نمیشود

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/postgah.com#1]
مشکل مشاهده و برطرف شد.
لطفا درصورتی که هنوز مشکلی هست اطلاع دهید

**Comment by postgah** [comment]
مشکل صفحه اصلی برطرف شد
ولی مشکل در زیر دسته ها موجود می باشد

**Comment by jalal7h** [comment]
در زیردسته ها هم الان اعمال شد
