### ISSUE TITLE
پاک کردن شهر تکراری مازندران

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#11]
بعد از اینکه شهر ها را از دمو به سایت اصلی انتقال دادید
در سیستم دو تا مازندران ثبت شده است
اونی که اگهی نداره لطفا پاک بشه

**Comment by jalal7h** [comment]
فقط یک مورد "مازندران" قابل مشاهده است
بظاهر خودتون حذف رو انجام دادید
@postgah
