### ISSUE TITLE
عدم تداخل تایتل اگهی و اخطار

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#14]
کادر 
اخطار! لطفا از واریز وجه به حساب فروشندگان ناشناس قبل از دسترسی مستقیم به کالا خودداری کنید.
زیر کادر تایتل اگهی باشد یعنی داخل کادر سفید نباشد و بتوان ان را بست

**Comment by jalal7h** [comment]
jash koja bashe?
yani ye box baraye TITLE bezarim
ye box baraye EKHTAR
va ye box baraye baghie?

@postgah

**Comment by postgah** [comment]
bbin box hoshdar dakhel box sefid ke title hast nabashe
biyad ziresh
yani az dakhel on box sefid dar biyad

**Comment by jalal7h** [comment]
انجام شد
و متنش از اینجا قابل ویرایش هست
http://postgah.com/?page=admin&cp=layout_mg&do=layer_form&id=93

@postgah 

![screen shot 2016-09-17 at 7 10 14 pm](https://cloud.githubusercontent.com/assets/15094271/18608885/62acb3aa-7d0a-11e6-921f-d93063c11add.jpg)
