### ISSUE TITLE
کادر کلمات کلیدی و آگهی های مرتبط

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#15]
این دو کادر از نظر دیزاین دقیقا شبیه فایل اصلی پی اس دی باشد

**Comment by jalal7h** [comment]
طبق درخواست انجام شد.
tori tanzim shod, k nesbat e tulo-arz hefz beshe, ezafash az gushe ha hazf beshe.

![screen shot 2016-09-12 at 12 27 10 am](https://cloud.githubusercontent.com/assets/15094271/18420095/e7a39842-787f-11e6-9d81-456a071169e8.jpg)
![screen shot 2016-09-12 at 12 28 38 am](https://cloud.githubusercontent.com/assets/15094271/18420096/e7a8e2a2-787f-11e6-8b12-42d87da2d523.jpg)
