### ISSUE TITLE
صفحات خالی برای نتایج سرچ

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#16]
![photo_2016-09-14_10-39-05](https://cloud.githubusercontent.com/assets/8435344/18501687/41e61798-7a20-11e6-9c0f-dc0127789e90.jpg)
اگه دقت کنید میبینید 2159 تا صفحه نتیجه اورده در صورتی که این مقدار نتیجه وجود ندارد و صفحات خالی می باشد
لطفا اصلاح و تعداد واقعی نتایج جستجو را نمایش دهد

**Comment by jalal7h** [comment]
این مشکل برطرف شد.

همچنین لینک های تگ که توی دیتابیس نیست دیگر از آدرس /tag/قابل مشاهده نخواهد بود
همچنین درصورت خالی بودن نتیجه جستجو پیام مناسب نمایش داده خواهد شد.

@postgah

**Comment by jalal7h** [comment]
![screen shot 2016-09-14 at 7 05 29 pm](https://cloud.githubusercontent.com/assets/15094271/18516429/3644420a-7aae-11e6-8bb3-fd42d13d1a70.jpg)
