### ISSUE TITLE
ری دایرکت کی وردس ها

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#18]
کی وردس ها که ری دایرکت که انجام میشه کلا نتیجه نمی یاره و فونت ها به هم میریزه

![screenshot from 2016-09-14 11-16-53](https://cloud.githubusercontent.com/assets/8435344/18502555/b50fb148-7a25-11e6-84f6-2724b1f6e6c8.png)

**Comment by jalal7h** [comment]
لطفا یک لینک تست بدید تا بررسی بشه
@postgah

**Comment by postgah** [comment]
http://www.postgah.com/pk=%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA%20%DB%8C%D8%AE%DA%86%D8%A7%D9%84%20%D9%BE%D9%BE%D8%B3%DB%8C

http://www.postgah.com/t=%D8%B5%D9%88%D8%B1%D8%AA%D8%AC%D9%84%D8%B3%D9%87%20%D8%AA%D8%AD%D9%88%DB%8C%D9%84%20%D8%AC%D9%87%DB%8C%D8%B2%DB%8C%D9%87/p=10023337.html

**Comment by jalal7h** [comment]
هم ویندوز
هم مک
تست گرفتم
این مشکل قابل مشاهده نیست
متاسفانه تا مشکل رو نبینم هیچ راه حل منطقی ندارم
@postgah 

![screen shot 2016-09-17 at 6 51 08 pm](https://cloud.githubusercontent.com/assets/15094271/18608775/d4589bd4-7d07-11e6-8d90-0e8746a5894a.jpg)
![screen shot 2016-09-17 at 6 51 16 pm](https://cloud.githubusercontent.com/assets/15094271/18608776/d480cd84-7d07-11e6-8aed-4ac8114ef9dc.jpg)
