### ISSUE TITLE
عنوان صفحه جستجو

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#19]
الام مثلا کلمه خرید موبایل را در سایت سرچ میکنیم صفحه نتایج که باز می شود
عنوان صفحه نتایج . عنوان صفه اصلی می باشد که نباید اینطور باشد

عنوان صفحه باید کلمه سرچ شده باشد و وقتی هم که صفحه بندی تغییر کرد عنوان هم تغییر کنید
به این صورت

خرید موبایل | پستگاه
خرید موبایل - صفحه 2 | پستگاه
خرید موبایل - صفحه 3 | پستگاه
و...

**Comment by jalal7h** [comment]
این از مدیریت سایت
بخش "طرح صفحه"قابل تنظیم است
انجام شد.

@postgah 

![screen shot 2016-09-17 at 6 46 52 pm](https://cloud.githubusercontent.com/assets/15094271/18608750/2a2e8132-7d07-11e6-9047-49797c658f66.jpg)

**Comment by postgah** [comment]
شماره صفحه تو تايتل هنوز نمي ياد و اين باعث ميشه تو گوكل كلي صفحات مختلف با تايتل يكسان بگيريم
