### ISSUE TITLE
صفحه 404

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#21]
صفحه 404 فعلی از نظر طراحی یک تافته جدا بافته هست
لطفا صفحه 404 در خود قالب سایت باشد

به این صورت 
http://www.sheypoor.com/searchYGG%D8%AF+%D9%85%D9%88%D8%A8%D8%A7%DB%8C%D9%84&c=&r=8

با این تفاوت که متن مربوط به 404 وسط چین گردد

**Comment by jalal7h** [comment]
زیبائی ۴۰۴ به جدا بافته بودنش هست
بسیار خب، از قالب سایت الگوبرداری خواهم کرد.
@postgah

**Comment by jalal7h** [comment]
انجام شد
@postgah 

![screen shot 2016-09-17 at 6 41 41 pm](https://cloud.githubusercontent.com/assets/15094271/18608720/66ce0ac8-7d06-11e6-87b9-57cf78169a83.jpg)

**Comment by jalal7h** [comment]
مشکل لینک "صفحه اصلی" برطرف شد.
@postgah
