### ISSUE TITLE
خطار در ثبت مدیر جدید

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#23]
در مدیریت در قسمت مدیران مدیر جدید ثبت نمی شود و خطا میدهد
یک فیلد هم در ان وجود دارد که معلوم نیست فیلد چه اطلاعاتی می باشد

**Comment by jalal7h** [comment]
مشکل برطرف شد
@postgah

**Comment by postgah** [comment]
زمان ثبت نام مدیر به درستی نمایش داده شود
![screenshot from 2016-09-18 01-06-32](https://cloud.githubusercontent.com/assets/8435344/18610839/f6318a12-7cf4-11e6-8a98-e1eca902bf77.png)
و مورد مشاهده اخرین فعالیت مدیر هم اضافه گرد
![1](https://cloud.githubusercontent.com/assets/8435344/18610864/9b07e93c-7cf5-11e6-9770-718d75875424.JPG)
