### ISSUE TITLE
عدم كار كرد پرداخت انلاين

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#25]
تنظيمات درگاه بانك ملت در مديريت و همچنين روند پرداخت هزينه پلن ها دچار مشكل مي باشد

**Comment by postgah** [comment]
لطفا به هم ریختگی فونت در مدیریت برطرف شود
![screenshot_20160917_144028](https://cloud.githubusercontent.com/assets/8435344/18611094/b4474052-7ce4-11e6-87a0-a74ad24a89ad.png)

مشکل افزایش اعتبار حساب از محیط کاربری برطرف شود
![screenshot_20160917_143859](https://cloud.githubusercontent.com/assets/8435344/18611097/c6a44cea-7ce4-11e6-9bc6-b43945536216.png)

**Comment by jalal7h** [comment]
مشکل برطرف شد.
@postgah 

![screen shot 2016-10-23 at 2 08 28 pm](https://cloud.githubusercontent.com/assets/15094271/19625620/4ee6cd88-992a-11e6-8b65-6a08b0712118.jpg)

**Comment by postgah** [comment]
مشکل به هم ریختگی فونت فونت در محیط مدیریت آن حل نشده است
![screenshot_20160917_144028](https://cloud.githubusercontent.com/assets/8435344/18611094/b4474052-7ce4-11e6-87a0-a74ad24a89ad.png)
@jalal7h
