### ISSUE TITLE
مشكل پلن ها

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#26]
پلن هاي اگهي پولي در مديريت تعريف مي شود ولي امكان خريد براي كاربر وجود ندارد

**Comment by jalal7h** [comment]
پلان ها پس از انتخاب دسته بندی قابلی مشاهده خواهد بود.
@postgah 
![screen shot 2016-10-22 at 11 27 15 pm](https://cloud.githubusercontent.com/assets/15094271/19622103/1577a728-98af-11e6-93da-983b8e8db1e5.jpg)

**Comment by postgah** [comment]
با سلام

یعد از کلیک بر روی پلن ها صفحه سفید می شود
به محیط کاربری میرم >> لیست آگهی ها >>  آگهی رو انتخاب میکنم برای ویژه کردن
![screenshot from 2016-10-23 22-26-11](https://cloud.githubusercontent.com/assets/8435344/19628647/e662cabc-9930-11e6-9adf-1c0e6269cdc3.png)
روی ثبت سفارش که کلیک میکنم صفحه سفید میشه و اتفاق خاصی رخ نمیدهد
![screenshot from 2016-10-23 22-27-37](https://cloud.githubusercontent.com/assets/8435344/19628773/1565fabc-9933-11e6-9c46-6d1210498afa.png)

---

مورد دوم اینکه پلن روی اگهی اجرا نمی شود
بنده یک پلن تعریف کردم و یک آگهی جدید ثبت کردم و پلن مربوطه را انتخاب کردم ولی بعد از فعال سازی در صدر گروه نمایش داده نشد
@jalal7h
