### ISSUE TITLE
ايميل تاييد عضويت 

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#27]
در مراحل ثبت نام ارسال ايميل تاييده وجود ندارد كه اين مورد خيلي مهمه

**Comment by jalal7h** [comment]
این مورد برای شما پیاده سازی شد.

![screen shot 2016-09-26 at 9 29 08 pm](https://cloud.githubusercontent.com/assets/15094271/18845886/5c85e88e-8430-11e6-818c-7eba7e6872c1.jpg)
![screen shot 2016-09-26 at 9 24 43 pm](https://cloud.githubusercontent.com/assets/15094271/18845896/63cd236e-8430-11e6-896c-b23d8820360b.jpg)

**Comment by jalal7h** [comment]
@postgah
