### ISSUE TITLE
مشکل ثبت مدیر جدید

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#28]
ثبت مدیر جدید دچار مشکل می باشد
![screenshot from 2016-09-18 00-12-50](https://cloud.githubusercontent.com/assets/8435344/18610570/d4ad11ba-7ced-11e6-8b6e-cf863d8cbfae.png)

**Comment by jalal7h** [comment]
این مورد در issue دیگری مطرح و برطرف شده است.
