### ISSUE TITLE
1 - فونت انتخاب استان ها برای قسمت جستجو ریزه

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/postgah.com#3]
بله
اما دقت داشته باشید
فونت رو که بزرگ میکنیم عرض باکس زیاد میشه و فضای زیادی رو میگیره

لطفا سایز مورد نظر رو بگید تا تنظیم کنم

![screen shot 2016-09-05 at 7 52 48 pm](https://cloud.githubusercontent.com/assets/15094271/18252129/586c4660-73a2-11e6-8bb1-b453136d527b.jpg)

**Comment by postgah** [comment]
خودتون یکی دو تا زیادش کنید ببینید کودم بهتر تر میشه همونو جایگزین کنید

**Comment by postgah** [comment]
لطفا انتخاب شهر این سایت رو هم ببینید
جالب و ساده و شیک
http://www.quikr.com/

**Comment by postgah** [comment]
این موضوع حل شده است و سایز فونت مناسب است
لطفا این موضوع بسته شود
@jalal7h

**Comment by jalal7h** [comment]
besyar khob, mersi
@postgah
