### ISSUE TITLE
صفحه تغییر گذرواژه  در مدیریت تکمیل شود

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#30]
صفحه تغییر گذرواژه تکمیل شود

**Comment by postgah** [comment]
![img_5249](https://cloud.githubusercontent.com/assets/8435344/18610832/c46900e6-7cf4-11e6-8e37-d1d8d38d6eee.JPG)

**Comment by jalal7h** [comment]
انجام شد
@postgah 

![screen shot 2016-10-24 at 12 02 39 am](https://cloud.githubusercontent.com/assets/15094271/19629262/36fddff6-997d-11e6-8209-f46feaffe2ef.jpg)
