### ISSUE TITLE
ثبت کاربر خالی - فرم ثبت نام

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#32]
به مدیریت به بخش کاربران مراجعه کنید
متوجه می شوید که کاربرانی بدونه هیچگونه مشخصاتی ثبت شده اند
و حتی پنل کاربری برای خود دارند
لطفا پیگیری کنید

**Comment by jalal7h** [comment]
بررسی شد 
مشکلی دیده نشد
عکس از مشکل ارسال کنید
@postgah

**Comment by postgah** [comment]
![screenshot from 2016-09-26 22-57-07](https://cloud.githubusercontent.com/assets/8435344/18848732/be65ffb8-83fd-11e6-86d5-e59fb20febbc.png)

**Comment by postgah** [comment]
مورد بعدی که الان متوجه شدم الزامی نبودن فیلد های ثبت نامه هست
اینجا مشاهده می کنید که کاربری ثبت شده که به درستی نا و نام خانوادگی وارد نکرده است
![screenshot from 2016-09-26 22-59-38](https://cloud.githubusercontent.com/assets/8435344/18848865/53cdd012-83fe-11e6-93f0-f627ce9cc230.png)

**Comment by jalal7h** [comment]
limit ruye vared kardan e nam ro darim
alan mitunid khodetun check konid.
karbar ta esm ro vared nakone register nemishe

@postgah

**Comment by jalal7h** [comment]
hamchenin, dar hale hazer, inke tuye field e esm, horuf e dorost estefade beshe check mishe alan
masalan .,:"(*&^%$# injur chiza tush bashe error mide be karbar : 
لطفا نام خود را به درستی وارد کنید.

@postgah

**Comment by postgah** [comment]
لطفا موارد زیر چک و در صورت نبود اعمال شود
1 - الزامی بودن تمام فیلد های ثبت نام
در صورت وارد نکردن اخطار دهد
2 - عدم امکان ثبت نام و نام خانوادگی به صورت انگلیسی 
3 - ولید سازی فیلد موبایل
در صورتی که تعداد ارقام کمتر از تعداد مجاز بود اخطار دهد
4 -  فیدل ایمیل هم به همین صورت دارای ولید سازی باشد
به فرض مثال @ 
وارد نشده باشد اخطار دهد یا زمانی ایمیل به درستی وارد نشده باشد اخطار دهد

**Comment by postgah** [comment]
یک سوال اینکه چه کاری میتوان کرد که کاربر هم اسم و هم فامیل خود را وارد کند
مشاهده می شود که کاربری فقط اسم خود را وارد میکند
و کاربری فقط فامیل

**Comment by postgah** [comment]
جناب حسینی این مورد رو فعلا کار نکنید روش چون من یک روند خیلی ساده تر از ثبت نام دیدم 
دوباره کاری میشه

**Comment by jalal7h** [comment]
1 - الزامی بودن تمام فیلد های ثبت نام
bejoz mobile hame field haye sabtenam ejbari hast.

2 - عدم امکان ثبت نام و نام خانوادگی به صورت انگلیسی 
anjam shod.

3 - ولید سازی فیلد موبایل
in ro nadarim, age mayelid anjam beshe.

4 - فیدل ایمیل هم به همین صورت دارای ولید سازی باشد
alan faal hast.

@postgah

**Comment by postgah** [comment]
ادامه این موضوع  با عنوان جدیدی پیگیری می شود
@jalal7h
