### ISSUE TITLE
عدم ارسال ایمیل ریکاوری - ضروری

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#33]
با توجه به تعویض سایت و اینکه بسیاری کاربران از این گزینه استفاده میکنند لطفا سریعتر برطرف شود

ایمیل ارسال نمی شود

**Comment by jalal7h** [comment]
این بخش انجام شد.
@postgah 

![screen shot 2016-09-18 at 11 56 33 pm](https://cloud.githubusercontent.com/assets/15094271/18618765/671c4150-7e02-11e6-8817-66cdc772849b.jpg)
![screen shot 2016-09-19 at 12 24 03 am](https://cloud.githubusercontent.com/assets/15094271/18618766/6722273c-7e02-11e6-8995-98f42da3fb80.jpg)
![screen shot 2016-09-19 at 12 24 41 am](https://cloud.githubusercontent.com/assets/15094271/18618767/6724b11e-7e02-11e6-9d92-3dea23f84833.jpg)
