### ISSUE TITLE
بخش نظرات سایت

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#34]
در صفحه شرح آگهی بعد از ثبت نظر قسمت امتیاز دهی  دچار مشکل می باشد

upvote_title = 'رای+';   رای+     پاسخ توئیت

و اینکه بهتر است نام کاربری نظر دهنده در کنار عکس ان نمایش داده شود

**Comment by postgah** [comment]
![screenshot_20160917_142900](https://cloud.githubusercontent.com/assets/8435344/18611053/1bb454a2-7ce3-11e6-945d-ad75e2d04566.png)

**Comment by jalal7h** [comment]
مشکل برطرف شد.
@postgah 

![screen shot 2016-10-22 at 10 55 59 pm](https://cloud.githubusercontent.com/assets/15094271/19621947/b958d182-98aa-11e6-9f41-b6e0999fe01f.jpg)
