### ISSUE TITLE
عدم نمایش عکس بند انگشتی جدید ترین اگهی های

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#35]
در صفحه مربوط به گروه ها
مثلا این صفحه
http://postgah.com/cat-121,0/%D8%B5%D9%86%D8%B9%D8%AA-%D9%88-%D8%AA%D8%AC%D8%A7%D8%B1%D8%AA.html
در کادر جدید ترین آگهی ها
عکس بند انگشتی موجود برای این اگهی ها لود نمی شود

![screenshot_20160917_143432](https://cloud.githubusercontent.com/assets/8435344/18611079/e7526d9c-7ce3-11e6-925e-0da3eecf8ca5.png)

**Comment by jalal7h** [comment]
این مشکل قبلا برطرف شد
@postgah 

![screen shot 2016-10-22 at 9 30 09 pm](https://cloud.githubusercontent.com/assets/15094271/19621432/b849965c-989e-11e6-9daa-49aecabb4f09.jpg)
