### ISSUE TITLE
عدم نمایش آگهی ها در محیط کاربری

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#37]
آگهی ها در محیط کاربری کاربران موجود نمی باشند

**Comment by jalal7h** [comment]
تصویر از مشکل ارائه بدید لطفا
همینطوری یه جمله ای میگید من دستم به جایی بند نیست که مشکل رو پیگیری کنم

**Comment by postgah** [comment]
مثلا ببینید
اکانت من  با نام کاربری
 arkantos147@yahoo.com
کلی آگهی داره که تو چند صفحه است
وارد محیط کاربری خودم که میشم
![screenshot from 2016-09-27 01-40-41](https://cloud.githubusercontent.com/assets/8435344/18853751/e63ceff8-8414-11e6-863a-f09f7b393d0c.png)
حالا وقتی رو صفحات دیگه مثلا صفحه دو کلیک میکنم اینطور میشه و آگهی ها رو نمی یاره
![screenshot from 2016-09-27 01-41-08](https://cloud.githubusercontent.com/assets/8435344/18853707/ac1498bc-8414-11e6-878f-120dcf5633f9.png)
@jalal7h

**Comment by jalal7h** [comment]
این مشکل برطرف شد.
@postgah
