### ISSUE TITLE
جابه جایی متون انگلیسی

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#38]
مورد اول مربوط میشه به زمانی که یه متن انگلیسی جستجو میکنی به صورت زیر به هم میریزه
من برای مثال web 
رو جستجو کردم اینطوری شد
![capture](https://cloud.githubusercontent.com/assets/8435344/18613525/c606057e-7d31-11e6-8d48-367d88054d10.PNG)
در صورتی که باید اینطوری باشه 
web < پستگاه

مورد دوم ترکیب متن فارسی و انگلیسی
![capture](https://cloud.githubusercontent.com/assets/8435344/18613556/37071c5e-7d32-11e6-8264-66b044c2b689.PNG)
که این مورد در زیر گروه ها هم وجود دارد لطفا ان هم برطرف شود
![capture](https://cloud.githubusercontent.com/assets/8435344/18613583/876cea70-7d32-11e6-8e6b-b668fbec7326.PNG)

**Comment by jalal7h** [comment]
این مشکل برطرف شد.
@postgah 

![screen shot 2016-10-22 at 11 43 37 pm](https://cloud.githubusercontent.com/assets/15094271/19622215/9dc79e9c-98b1-11e6-84e4-18d96df35096.jpg)
![screen shot 2016-10-22 at 11 43 57 pm](https://cloud.githubusercontent.com/assets/15094271/19622217/a3fc5f5a-98b1-11e6-8d29-a88ab149ec68.jpg)
