### ISSUE TITLE
http://postgah.com/page-1.html

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#39]
در صفحه اصلی زمانی که بر روی صفحه اصلی کلیک می شود
![capture](https://cloud.githubusercontent.com/assets/8435344/18613608/fcd2c474-7d32-11e6-879a-b8844e313a2b.PNG)
به لینک زیر می رود
http://postgah.com/page-1.html
که باز همان صفحه اصلی

وجود چندین لینک مختلف برای یک صفحه به خصوص صفحه اصلی از دید گوگل اسپم می باشد
لطفا این لینک اصلا شود
و در صورت وجود مورد های مشابه از
tag canonical
استفاده شود

**Comment by postgah** [comment]
در صفحه عضویت همین مورد هست
http://postgah.com/login
![capture](https://cloud.githubusercontent.com/assets/8435344/18613642/9fe1a1e4-7d33-11e6-9d5c-04c7a83a409e.PNG)
که روی ورود کاربر کلیک کنید لینک به این تغییر پیدا میکنه
http://postgah.com/page-60.html

**Comment by jalal7h** [comment]
canonical dashtim, ama link tekrari midad
moshkel betore kamel hal shod.
shaiad jaleb bashe, in mored zaman e ziadi bord 

@postgah
