### ISSUE TITLE
کادر انتاخب استان با کادر جستجو نا هماهنگی

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/postgah.com#4]
2  - کادر انتاخب استان با کادر جستجو نا هماهنگی داره و بالا پایینه4

![screen shot 2016-09-05 at 7 53 39 pm](https://cloud.githubusercontent.com/assets/15094271/18252153/765adc04-73a2-11e6-8081-81af9fb985a5.jpg)

**Comment by postgah** [comment]
![screenshot from 2016-09-06 13-32-31](https://cloud.githubusercontent.com/assets/8435344/18267915/6b22da7e-73ef-11e6-8535-7c128545d8f3.png)

**Comment by postgah** [comment]
مرورگر فایر فاکس

**Comment by postgah** [comment]
این موضوع فقط در سیستم عامل لینوکس می باشد و مهم نیست
بنده با ویندوز چک کردم اوکی هست
لطفا این موضوع بسته شود
@jalal7h
