### ISSUE TITLE
عدم نمایش تگ کیوردس و دسکریپشن گروه ها و زیر گروه ها

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#40]
تگ کیوردس و دسکریپشن برای همه گرو ها یکسان می باشد 
در صورتی که باید برای هر گروه همانی باشد که در ادمین تعریف میکنیم

**Comment by jalal7h** [comment]
انجام شد

![screen shot 2016-09-26 at 11 30 23 pm](https://cloud.githubusercontent.com/assets/15094271/18849755/533e8f04-8441-11e6-924b-896fa6cc5af7.jpg)
@postgah
