### ISSUE TITLE
نمایش آگهی تایید نشده

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#41]
آگهی که هنوز تایید نشده است و در مدیریت منتظر تایید می باشد در صفحه اصلی نمایش داده می شود
و زمانی که روی آن کلیک میکنیم به صفحه 404 می رود

**Comment by jalal7h** [comment]
میشه یه عکس بدید از این لیست
که بدونم کجای سایت دیده میشه؟
مرسی
@postgah

**Comment by jalal7h** [comment]
![screen shot 2016-09-26 at 11 44 42 pm](https://cloud.githubusercontent.com/assets/15094271/18850168/37e79bb8-8443-11e6-9e00-1e32e68d3c79.jpg)

**Comment by jalal7h** [comment]
مشکل برطرف شد.
@postgah
