### ISSUE TITLE
خطا در هنگام ویرایش آگهی ثبت شده

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#42]
بعد از ورود به پنل کاربری و بر روی دکمه ویرایش آگهی که کلیک میکنیم و تغییرات رو که اعمال میکنیم 
و دکمه ثبت تغییرات رو که میزنیم ارور زیر را میدهد
![screenshot from 2016-09-26 23-34-49](https://cloud.githubusercontent.com/assets/8435344/18850262/bdfa9c1c-8404-11e6-9fe4-17c877a138fa.png)

**Comment by jalal7h** [comment]
مشکل برطرف شد.

![screen shot 2016-09-27 at 12 08 23 am](https://cloud.githubusercontent.com/assets/15094271/18850927/862c6706-8446-11e6-83e4-eef2f58dfbcd.jpg)
@postgah
