### ISSUE TITLE
ثبت اسم و فامیل در فرم ثبت نام

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/postgah.com#43]
یک سوال اینکه چه کاری میتوان کرد که کاربر هم اسم و هم فامیل خود را وارد کند
مشاهده می شود که کاربری فقط اسم خود را وارد میکند
و کاربری فقط فامیل

**Comment by jalal7h** [comment]
یا باید ۲ فیلد مجزا برای اسم و فامیل در نظر بگیریم و هردو رو اجباری کنیم
و یا اینکه اجبار ایجاد کنیم که در فیلد اسم کارکتر فاصله حتما باشه

@postgah

**Comment by postgah** [comment]
دو تا فیلد باشه  بهتره 
  فیلد های نام و نام خانوادگی کنار هم باشند
نه زیر هم

یا هم که برای جلویری از شلوغی فرم ثبت نام همین حالت بذاریم بمونه
خودتون برای این موضوع تصمیم بگیرید
هر کاری صلاحه انجام بدید
@jalal7h

**Comment by jalal7h** [comment]
بنظرم همین حالت که هست بمونه، چون : 
- با کاربران فعلی نمیدونیم باید چه کرد
- کسی که بخواد فامیلی شو وارد نکنه درهرصورت نمیکنه، چه دو بخش باشه چه نباشه

منتظر نظر شما هستم.

**Comment by postgah** [comment]
موردی ندارد
همین روال بماند

@jalal7h
