### ISSUE TITLE
عدم رفتن به منتظر تایید

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#45]
بعد از ویرایش آگهی در محیط کاربری
 آگهی به حالت منتظر تایید تبدیل نمی شود

آگهی برای تایید مجدد در مدیریت می آید
ولی در محیط کاربری وضعیت آن به منتظر تایید تغییر پیدا نمی کند

**Comment by jalal7h** [comment]
دلیل این مسئله این بوده که این بخش طوری تنظیم بوده که درصورتی که با حساب مدیریت لاگین بوده باشید آگهی بحالت غیرفعال وارد نشود.
البته برای جلوگیری از ایجاد ابهام این بخش غیرفعال شد.
@postgah

**Comment by postgah** [comment]
سلام
من چک کردم باز تایید می شد.
اگه زمانی که با ادمین وارد می شویم به اینگونه می باشد مشکلی ندارد 
@jalal7h

**Comment by jalal7h** [comment]
لطفا درصورت امکان این مورد را یکبار دیگر بصورت واضح توضیح دهید تا بررسی شود
@postgah

**Comment by postgah** [comment]
این مورد انجام شده است
