### ISSUE TITLE
عدم لینک شدن شماره تلفن ها 

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#48]
![selection_016](https://cloud.githubusercontent.com/assets/8435344/18931706/518c09b0-859b-11e6-9713-f444c545b040.png)

زمانی که روی شماره تلفن ها کلیک می شود به عنوان یک لینک جدید باز می شوند
اینطور نباید باشد و باید یک تکس معمولی باشد و اگر امکانش هست طوری شود که توسط ربات ها قابل کپی نباشد

**Comment by jalal7h** [comment]
ba standard e tel baz mishe
ru gushi rush click beshe mire ru call
baresh daram?!
@postgah

**Comment by postgah** [comment]
age standard ee khode html ee na moshkli nist bemone
