### ISSUE TITLE
مرتب کردن فوتر

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#51]
فوتر به همین روالی که هست از نظر چیدمان خواهد ماند

ما سه ستون لینک بیشتر نیاز نداریم که آن ها را ایجاد کرده ام

تغییرات مورد نیاز در فوتر

1 - مرتب و شکیل کردن ای نماد و لوگو به پرداخت
2 - بررسی عدم کار کرد ای نماد
3 - اضافه کردن ایکون های زیر به آیکون های موجود شبکه های اجتماعی
آیکون آپارات - ایکون ار اس اس اخبار - آیکون آر اس اس آگهی ها - آیکون سایت مپ سایت

**Comment by jalal7h** [comment]
anjam shod.
@postgah
