### ISSUE TITLE
بخش ورود و عضویت سایت و ریکاوری پسورد و ارسال ایمیل هنوز فعال نیست

### ISSUE THREAD

**Issue by postgah** [jalal7h/postgah.com#9]

**Comment by jalal7h** [comment]
بخش ورود و عضویت سایت بررسی و رفع اشکال شد.
@postgah

**Comment by postgah** [comment]
با سلام

مشکل هنوز پا بر جاست
![screenshot from 2016-09-14 10-14-29](https://cloud.githubusercontent.com/assets/8435344/18501604/c23d8d32-7a1f-11e6-8fd7-f6a14325695e.png)

لازم به ذکر می باشد ریکاوری رمز هم کار نمیکند بعد از ریکاوری پیغامی مبنی بر ارسال ایمیل  نمایش داده نمی شود و ایمیل ارسال نمی شود

**Comment by postgah** [comment]
dbs : 10604 (Duplicate entry 'arkantos148@gmail.com' for key 'username')
UPDATE `users` SET `username`='arkantos148@gmail.com',`password`='00110022',`name`='مهران خرمی',`cell`='09125410218' WHERE `id`='44159'

این ارور زمانی رخ میدهد که من با ایمیل زیر ثبت نام میکنم
arkantos148@gmail.com
لازم به ذکر می باشد که این ایمیل قبلا در سیستم عضو بوده ولی من از مدیریت ان را حذف کرده ام

برای این گونه کاربرانچگونه برخوردی می شود
به عنوان یوزر جدید در نظر گرفته می شود و یا یوزر که دیگر حق ثبت نام ندارد

لطفا ارور مربوطه برطرف گردد
